# Test config file
duplex:
  port: 9380

logger:
  log_path: ../logs
  log_file: server
  log_level: 7
  cons_level: 7
  source: false

handlers:
  - command:
      device_name: client
      binary_file: client.exe
      config_file: cliemt.yml
      logger_path: ../logs
      database:
      auto_load: true
    reflexes:
      - plugin_name: plugin_1
        enabled: true
      - plugin_name: plugin_2
        enabled: true
      - plugin_name: plugin_3
        enabled: false
  - command:
      device_name: cashcode
      binary_file: cashcode.exe
      config_file: cashcode.yml
      logger_path: ../logs
      database:
      auto_load: false
    reflexes:
      - plugin_name: plugin_1
        enabled: true


